// <auto-generated />
namespace GameLeaderboard.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update02 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update02));
        
        string IMigrationMetadata.Id
        {
            get { return "201903091357422_update02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
